### ISSUE TITLE
option to mount config as volume

### ISSUE THREAD

**Issue by Zolmeister** [tutumcloud/tutum-docker-influxdb#34]
Instead of exposing all config via environment variables, support a mount-point for config

```bash
docker run -v /etc/influxdb:/etc/influxdb -e CONFIG=/etc/influxdb/config.toml timtim/influxdb
```

**Comment by tifayuki** [comment]
You can mount a file:

    docker run -v /<yourpath>/config.toml:/config/config.toml tutum/influxdb
